export const GOODS = [
  { id: '1', name: 'Box1', imgUrl: 'src/assets/box.jpg', status: 1, minPrice: 100, maxPrice: 200 },
  {
    id: '2',
    name: 'Box2',
    imgUrl: 'src/assets/box - Copy.jpg',
    status: 1,
    minPrice: 150,
    maxPrice: 250,
  },
  {
    id: '3',
    name: 'Box3',
    imgUrl: 'src/assets/box - Copy (2).jpg',
    status: 1,
    minPrice: 120,
    maxPrice: 220,
  },
  {
    id: '4',
    name: 'Box4',
    imgUrl: 'src/assets/box - Copy (3).jpg',
    status: 1,
    minPrice: 80,
    maxPrice: 180,
  },
  {
    id: '5',
    name: 'Box5',
    imgUrl: 'src/assets/box - Copy (4).jpg',
    status: 0,
    minPrice: 200,
    maxPrice: 300,
  },
  {
    id: '6',
    name: 'Box6',
    imgUrl: 'src/assets/box - Copy (5).jpg',
    status: 1,
    minPrice: 90,
    maxPrice: 190,
  },
  {
    id: '7',
    name: 'Box7',
    imgUrl: 'src/assets/box - Copy (6).jpg',
    status: 1,
    minPrice: 110,
    maxPrice: 210,
  },
  {
    id: '8',
    name: 'Box8',
    imgUrl: 'src/assets/box - Copy (7).jpg',
    status: 0,
    minPrice: 130,
    maxPrice: 230,
  },
  {
    id: '9',
    name: 'Box9',
    imgUrl: 'src/assets/box - Copy (8).jpg',
    status: 1,
    minPrice: 140,
    maxPrice: 240,
  },
  {
    id: '10',
    name: 'Box10',
    imgUrl: 'src/assets/box - Copy (9).jpg',
    status: 1,
    minPrice: 160,
    maxPrice: 260,
  },
]
